services:
  web:
    container_name: swaggerservice
    build: .
    ports:
      - "8450:8450"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongo

  mongo:    
    container_name: mongodb 
    image: mongo:latest
    restart: always
