version: '3.8'
services:
  web:
    build: .
    ports:
      - "8450:8450"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
